os: linux
dist: focal

language: node_js
node_js:
- 6.14.0
- 14.17.4
- 16

# Set the API key for the integration tests. In the future, all tests will rely on snapshots. An API key will then only
# be required to update those snapshots. The API key can then be removed from this file.
env:
  - API_KEY=test_4kQQbBMEFh8QAuKVaWdpKuRpVSsdVG

# Some modules used require a greater Node.js version than the lowest supported (listed above). Switch to Node.js
# v12.×.× before installing to game the system, and switch back before running the actual tests.
before_install:
  - >
    if $(dpkg --compare-versions "${TRAVIS_NODE_VERSION}" "lt" "8.10.0"); then
      nvm use v10.16.0
    fi

before_script:
  - nvm use ${TRAVIS_NODE_VERSION}